### PR TITLE
Support cross compile to sbt 0.13.16 and 1.1.0

### PR DESCRIPTION
**Pull request by pellekrogholt**
# Changes
- support of sbt 1.1.0
- cross compile to sbt "0.13.16", "1.1.0"

### CODE REVIEW

**Comment by sakoht** [comment]
Sweet.

**Comment by piotrglazar** [comment]
Can we merge this PR? We could really use it in our projects.

**Comment by pellekrogholt** [comment]
@piotrglazar I dont have the force to merge so you have to poke some of the people of hmrc: https://github.com/orgs/hmrc/people

**Comment by ryanberckmans** [comment]
@tomasz-rosiek can we merge this PR? Thanks!

**Comment by ritvikgautam** [comment]
Bump! Also, sbt is now on `1.3.3`. 

@chotai @fayimora @konradwudkowski @LGoldfinch2 @michaelmeasures @robertbutacu @seane

**Comment by bennetimo** [comment]
Thanks for the PR, the plugin is now cross-built for sbt `1.3.4` as of version `6.0.0`

**Pull request closed without merging**
